import './persistAppState';
import './controlBar';
import './customTheme';
import './desktopSettings';
import './errorHandler';
import './tray';
import './autoUpdater';
import './websocketAPI';
import './applicationMenu';
import './windowTitleInfo';
// import './keyboardShortcuts';
// import './lastFM';
