export default {
  SIDEBAR_OPEN: 'SIDEBAR_OPEN',
  SIDEBAR_CLOSE: 'SIDEBAR_CLOSE',
  SIDEBAR_TOGGLE: 'SIDEBAR_TOGGLE',

  SETUP_FINISHED: 'SETUP_FINISHED',

  MODAL_TOGGLE_ABOUT: 'MODAL_TOGGLE_ABOUT',
  MODAL_TOGGLE_HELP: 'MODAL_TOGGLE_HELP'
}
